package sdkclient

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v5"
)

func TestSDKProtocolSchemaAcceptsReferenceNotificationsAndClientRequests(t *testing.T) {
	notificationSchema := compileProtocolDefinition(t, "notification")
	requestSchema := compileProtocolDefinition(t, "request")
	for _, surfaceOp := range []string{`"append"`, `{"op":"replace","start":3,"end":5}`} {
		frame := []byte(fmt.Sprintf(`{"jsonrpc":"2.0","method":"session.event","params":{"sessionId":"s","event":{"type":"user/message","seq":7,"time":12,"data":{"content":[]},"surfaceOp":%s}}}`, surfaceOp))
		if err := notificationSchema.Validate(bytesReader(frame)); err != nil {
			t.Fatalf("surface operation %s rejected by schema: %v", surfaceOp, err)
		}
	}
	referenceRoot := os.Getenv("SHUTU_REFERENCE_ROOT")
	if referenceRoot == "" {
		referenceRoot = filepath.Clean(filepath.Join("..", "..", ".reference", "dsh"))
	}
	if _, err := os.Stat(referenceRoot); err != nil && os.Getenv("SHUTU_REFERENCE_ROOT") == "" {
		t.Log("optional DeepSeek Harness reference snapshots unavailable; skipped")
	} else {
		for _, scenario := range []string{"text-turn", "bash-tool", "persistent-tools", "subagent-spawn-in-process"} {
			path := filepath.Join(referenceRoot, "examples", "jsonrpc-agent", "tests", "snapshots", scenario, "notifications.expected.jsonl")
			for _, notification := range loadReferenceNotifications(t, path) {
				frame, err := json.Marshal(struct {
					JSONRPC string          `json:"jsonrpc"`
					Method  string          `json:"method"`
					Params  json.RawMessage `json:"params"`
				}{JSONRPC: "2.0", Method: notification.Method, Params: notification.Params})
				if err != nil {
					t.Fatal(err)
				}
				if err := notificationSchema.Validate(bytesReader(frame)); err != nil {
					t.Fatalf("%s notification rejected by schema: %v\n%s", scenario, err, frame)
				}
			}
		}
	}

	typedPrompt := SessionPromptParams{
		SessionID: "s",
		ContentBlocks: []ContentBlock{
			TextContent("hello"),
			ReasoningContent("thought"),
			ImageAttachmentContent(ImageAttachmentRef{AttachmentID: "attachment-1", MediaType: "image/png", Bytes: 2, Width: 1, Height: 1}),
			ToolCallContent("call-1", "read", "{}"),
			ToolResultContent("call-1", []ContentBlock{TextContent("ok")}, false),
			{Raw: json.RawMessage(`{"type":"x-plugin/block","payload":{"opaque":true}}`)},
		},
	}
	typedPromptRaw, err := json.Marshal(typedPrompt)
	if err != nil {
		t.Fatal(err)
	}
	requests := []wireRequest{
		{JSONRPC: "2.0", ID: "go-1", Method: "initialize", Params: json.RawMessage(`{"cwd":"D:\\workspace","provider":"deepseek-official","model":"deepseek-v4-flash","maxTokens":128}`)},
		{JSONRPC: "2.0", ID: "go-2", Method: "session/prompt", Params: typedPromptRaw},
		{JSONRPC: "2.0", ID: "go-3", Method: "session/snapshot", Params: json.RawMessage(`{"sessionId":"s"}`)},
		{JSONRPC: "2.0", ID: "go-4", Method: "shutdown"},
	}
	for _, request := range requests {
		raw, err := json.Marshal(request)
		if err != nil {
			t.Fatal(err)
		}
		if err := requestSchema.Validate(bytesReader(raw)); err != nil {
			t.Fatalf("request rejected by schema: %v\n%s", err, raw)
		}
	}
}

func TestSDKProtocolSchemaMatchesReferenceGeneratedArtifact(t *testing.T) {
	referenceRoot := os.Getenv("SHUTU_REFERENCE_ROOT")
	if referenceRoot == "" {
		t.Skip("opt-in schema drift gate requires SHUTU_REFERENCE_ROOT")
	}
	referenceRoot = filepath.Clean(referenceRoot)
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	generated := filepath.Join(t.TempDir(), "protocol.schema.json")
	command := exec.Command("node", filepath.Join(repoRoot, "tools", "generate-sdk-protocol-schema.mjs"), generated)
	command.Env = append(os.Environ(), "SHUTU_REFERENCE_ROOT="+referenceRoot)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("generator failed: %v\n%s", err, output)
	}
	checkedIn, err := os.ReadFile(filepath.Join("testdata", "protocol.schema.json"))
	if err != nil {
		t.Fatal(err)
	}
	refreshed, err := os.ReadFile(generated)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(checkedIn, refreshed) {
		t.Fatalf("checked-in SDK schema drifted from reference TS types\n%s", strings.Join([]string{
			fmt.Sprintf("checked-in bytes: %d", len(checkedIn)),
			fmt.Sprintf("generated bytes: %d", len(refreshed)),
			"regenerate with: node tools/generate-sdk-protocol-schema.mjs",
		}, "\n"))
	}
}

func TestSDKProtocolSchemaRejectsInvalidShapes(t *testing.T) {
	tests := []struct {
		def    string
		raw    string
		reason string
	}{
		{"notification", `{"jsonrpc":"2.0","method":"session.event","params":{"sessionId":"s","event":{"type":"turn/start","seq":0,"time":"0"}}}`, "event time must be numeric"},
		{"notification", `{"jsonrpc":"2.0","method":"session.status","params":{"sessionId":"s","status":"stopped"}}`, "status vocabulary is closed"},
		{"notification", `{"jsonrpc":"2.0","method":"subagent.started","params":{"parentSessionId":"p"}}`, "subagent start requires child"},
		{"request", `{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"cwd":"","maxTokens":0}}`, "initialize requires cwd and positive maxTokens"},
		{"request", `{"jsonrpc":"2.0","id":"1","method":"session/prompt","params":{"sessionId":"s","contentBlocks":[{"type":"image"}]}}`, "known image block requires attachment"},
		{"request", `{"jsonrpc":"2.0","id":"1","method":"session/prompt","params":{"sessionId":"s","contentBlocks":[{"type":"tool-call"}]}}`, "known tool-call block requires identity"},
		{"promptResult", `{"messageId":""}`, "prompt result requires message id"},
		{"shutdownResult", `{"unexpected":true}`, "shutdown result is empty"},
	}
	for _, test := range tests {
		schema := compileProtocolDefinition(t, test.def)
		if err := schema.Validate(bytesReader([]byte(test.raw))); err == nil {
			t.Fatalf("schema accepted invalid %s: %s", test.reason, test.raw)
		}
	}
}

func TestSDKTypedResultsAreSchemaValid(t *testing.T) {
	initializeSchema := compileProtocolDefinition(t, "initializeResult")
	promptSchema := compileProtocolDefinition(t, "promptResult")
	shutdownSchema := compileProtocolDefinition(t, "shutdownResult")

	var initialize InitializeResult
	initialize.ServerInfo.Name = "shutu-agent-sdk-runtime"
	initialize.ServerInfo.Version = "test"
	raw, err := json.Marshal(initialize)
	if err != nil {
		t.Fatal(err)
	}
	if err := initializeSchema.Validate(bytesReader(raw)); err != nil {
		t.Fatal(err)
	}
	// The optional catalog extension must remain compatible with the reference
	// result shape rather than replacing the required server identity.
	initialize.ToolCatalog = &ToolCatalog{
		SchemaVersion: 1, Revision: 7, Digest: "digest-7",
		Tools: []ToolCatalogEntry{{Name: "read", Profile: "standard", Provenance: "builtin", Generation: 7, Visible: true}},
	}
	raw, err = json.Marshal(initialize)
	if err != nil {
		t.Fatal(err)
	}
	if err := initializeSchema.Validate(bytesReader(raw)); err != nil {
		t.Fatalf("tool catalog extension is not schema-compatible: %v", err)
	}
	raw, err = json.Marshal(SessionPromptResult{MessageID: "message-1"})
	if err != nil {
		t.Fatal(err)
	}
	if err := promptSchema.Validate(bytesReader(raw)); err != nil {
		t.Fatal(err)
	}
	raw, err = json.Marshal(map[string]any{})
	if err != nil {
		t.Fatal(err)
	}
	if err := shutdownSchema.Validate(bytesReader(raw)); err != nil {
		t.Fatal(err)
	}
}

func compileProtocolDefinition(t *testing.T, definition string) *jsonschema.Schema {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "protocol.schema.json"))
	if err != nil {
		t.Fatal(err)
	}
	compiler := jsonschema.NewCompiler()
	const base = "https://shutu.local/sdk/protocol.json"
	if err := compiler.AddResource(base, bytes.NewReader(raw)); err != nil {
		t.Fatal(err)
	}
	wrapper := []byte(fmt.Sprintf(`{"$ref":%q}`, base+"#/$defs/"+definition))
	if err := compiler.AddResource("https://shutu.local/sdk/definition.json", bytes.NewReader(wrapper)); err != nil {
		t.Fatal(err)
	}
	schema, err := compiler.Compile("https://shutu.local/sdk/definition.json")
	if err != nil {
		t.Fatal(err)
	}
	return schema
}

func bytesReader(raw []byte) any {
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return nil
	}
	return value
}
