package projection

import (
	"encoding/json"
	"errors"
	"sort"

	"github.com/shutu-ai/shutu-agent/internal/session"
)

// EventSurface is the query-facing placement of one durable event.  It is
// derived from the same ordered event stream as Snapshot.History; callers must
// not infer shadowing by scanning replacement payloads themselves.
type EventSurface string

const (
	SurfaceCurrent  EventSurface = "current"
	SurfaceShadowed EventSurface = "shadowed"
	SurfaceLogOnly  EventSurface = "log-only"
)

// ClassifyEventSurfaces validates and classifies every event in one durable
// stream.  Replacement ranges are applied in append order, so a later
// replacement can shadow an earlier replacement marker as well.  The returned
// map is detached and keyed by the durable sequence number.
func ClassifyEventSurfaces(events []session.Event) (map[uint64]EventSurface, error) {
	if _, err := Build(events); err != nil {
		return nil, err
	}

	out := make(map[uint64]EventSurface, len(events))
	for _, event := range events {
		if isLogOnlyEvent(event.Type) {
			out[event.Seq] = SurfaceLogOnly
		} else {
			out[event.Seq] = SurfaceCurrent
		}
	}
	for _, event := range events {
		replacement, ok := session.SurfaceReplacement(event)
		if !ok {
			continue
		}
		for _, target := range events {
			if target.Seq >= uint64(replacement.Start) && target.Seq <= uint64(replacement.End) {
				out[target.Seq] = SurfaceShadowed
			}
		}
	}
	return out, nil
}

// EventRelations is the query-facing causal view of one durable event. It is
// derived from the same validated stream as Build, so transport tools cannot
// grow a second interpretation of replacement ranges or tool-call edges.
type EventRelationSet struct {
	// ReplacedBy is the earliest later replacement marker that shadows the
	// target event, or zero when the target remains current.
	ReplacedBy uint64
	// ReplacementChain follows successive replacement markers beyond ReplacedBy.
	ReplacementChain []uint64
	// Replaces contains the other durable events shadowed when the target is
	// itself a replacement marker.
	Replaces []uint64
	// Sources are direct assistant/tool-call events cited by the target.
	Sources []uint64
	// Derived are direct tool-call/tool-result events generated by the target.
	Derived []uint64
}

// EventRelations validates the complete durable stream, then derives the
// replacement and tool-call relations for targetSeq through the shared
// projection vocabulary. It never invents relations for malformed streams.
func EventRelations(events []session.Event, targetSeq uint64) (EventRelationSet, error) {
	if _, err := Build(events); err != nil {
		return EventRelationSet{}, err
	}
	var target *session.Event
	bySeq := make(map[uint64]session.Event, len(events))
	for i := range events {
		bySeq[events[i].Seq] = events[i]
		if events[i].Seq == targetSeq {
			target = &events[i]
		}
	}
	if target == nil {
		return EventRelationSet{}, errors.New("projection: target event not found")
	}

	var result EventRelationSet
	for i := range events {
		event := events[i]
		if event.Seq == targetSeq {
			continue
		}
		replacement, ok := session.SurfaceReplacement(event)
		if !ok || targetSeq < uint64(replacement.Start) || targetSeq > uint64(replacement.End) {
			continue
		}
		if result.ReplacedBy == 0 || event.Seq < result.ReplacedBy {
			result.ReplacedBy = event.Seq
		}
	}

	current := targetSeq
	seen := map[uint64]bool{current: true}
	for {
		var next uint64
		for i := range events {
			event := events[i]
			replacement, ok := session.SurfaceReplacement(event)
			if !ok || event.Seq <= current || current < uint64(replacement.Start) || current > uint64(replacement.End) {
				continue
			}
			if next == 0 || event.Seq < next {
				next = event.Seq
			}
		}
		if next == 0 || seen[next] {
			break
		}
		result.ReplacementChain = append(result.ReplacementChain, next)
		seen[next] = true
		current = next
	}

	if replacement, ok := session.SurfaceReplacement(*target); ok {
		for i := range events {
			event := events[i]
			if event.Seq != targetSeq && event.Seq >= uint64(replacement.Start) && event.Seq <= uint64(replacement.End) {
				result.Replaces = append(result.Replaces, event.Seq)
			}
		}
	}

	targetCall, targetAssistantCalls := eventCallRefs(*target)
	for i := range events {
		event := events[i]
		if event.Seq == targetSeq {
			continue
		}
		call, assistantCalls := eventCallRefs(event)
		if targetCall != "" && (target.Type == session.EventToolResult || target.Type == session.EventToolError) &&
			event.Type == session.EventToolStart && call == targetCall {
			result.Sources = append(result.Sources, event.Seq)
		}
		if targetCall != "" && target.Type == session.EventToolStart && event.Type == session.EventAssistantMessage &&
			containsString(assistantCalls, targetCall) {
			result.Sources = append(result.Sources, event.Seq)
		}
		if targetCall != "" && target.Type == session.EventToolStart &&
			(event.Type == session.EventToolResult || event.Type == session.EventToolError) && call == targetCall {
			result.Derived = append(result.Derived, event.Seq)
		}
		if len(targetAssistantCalls) > 0 && event.Type == session.EventToolStart && containsString(targetAssistantCalls, call) {
			result.Derived = append(result.Derived, event.Seq)
		}
	}
	sort.Slice(result.Replaces, func(i, j int) bool { return result.Replaces[i] < result.Replaces[j] })
	sort.Slice(result.Sources, func(i, j int) bool { return result.Sources[i] < result.Sources[j] })
	sort.Slice(result.Derived, func(i, j int) bool { return result.Derived[i] < result.Derived[j] })
	return result, nil
}

func eventCallRefs(event session.Event) (string, []string) {
	switch event.Type {
	case session.EventToolStart, session.EventToolResult:
		var wire struct {
			CallID string `json:"callId"`
		}
		_ = json.Unmarshal(event.Data, &wire)
		return wire.CallID, nil
	case session.EventAssistantMessage:
		var wire struct {
			ToolCalls []struct {
				ID string `json:"ID"`
			} `json:"toolCalls"`
		}
		_ = json.Unmarshal(event.Data, &wire)
		ids := make([]string, 0, len(wire.ToolCalls))
		for _, call := range wire.ToolCalls {
			if call.ID != "" {
				ids = append(ids, call.ID)
			}
		}
		return "", ids
	default:
		return "", nil
	}
}

func containsString(values []string, needle string) bool {
	for _, value := range values {
		if value == needle {
			return true
		}
	}
	return false
}

func isLogOnlyEvent(typ string) bool {
	for _, prefix := range []string{"turn/", "step/", "llm/", "subagent/", "workflow/", "goal/", "compaction/", "job/", "terminal/", "eval/", "schedule/", "feedback/"} {
		if len(typ) >= len(prefix) && typ[:len(prefix)] == prefix {
			return true
		}
	}
	return false
}
